// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package ir

import "encoding/json"
import "fmt"
import "reflect"
import "time"

// A single HTTP request/response capture.
type IRRecord struct {
	// Round-trip time in milliseconds.
	DurationMs *float64 `json:"durationMs,omitempty" yaml:"durationMs,omitempty" mapstructure:"durationMs,omitempty"`

	// Unique identifier for this record (e.g., UUID).
	Id *string `json:"id,omitempty" yaml:"id,omitempty" mapstructure:"id,omitempty"`

	// Request corresponds to the JSON schema field "request".
	Request Request `json:"request" yaml:"request" mapstructure:"request"`

	// Response corresponds to the JSON schema field "response".
	Response Response `json:"response" yaml:"response" mapstructure:"response"`

	// Adapter/source that generated this record.
	Source *IRRecordSource `json:"source,omitempty" yaml:"source,omitempty" mapstructure:"source,omitempty"`

	// ISO 8601 timestamp of the request capture.
	Timestamp *time.Time `json:"timestamp,omitempty" yaml:"timestamp,omitempty" mapstructure:"timestamp,omitempty"`
}

type IRRecordSource string

const IRRecordSourceHar IRRecordSource = "har"
const IRRecordSourceLoggingTransport IRRecordSource = "logging-transport"
const IRRecordSourceManual IRRecordSource = "manual"
const IRRecordSourcePlaywright IRRecordSource = "playwright"
const IRRecordSourceProxy IRRecordSource = "proxy"

var enumValues_IRRecordSource = []interface{}{
	"har",
	"playwright",
	"logging-transport",
	"proxy",
	"manual",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *IRRecordSource) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_IRRecordSource {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_IRRecordSource, v)
	}
	*j = IRRecordSource(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *IRRecord) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["request"]; raw != nil && !ok {
		return fmt.Errorf("field request in IRRecord: required")
	}
	if _, ok := raw["response"]; raw != nil && !ok {
		return fmt.Errorf("field response in IRRecord: required")
	}
	type Plain IRRecord
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.DurationMs != nil && 0 > *plain.DurationMs {
		return fmt.Errorf("field %s: must be >= %v", "durationMs", 0)
	}
	*j = IRRecord(plain)
	return nil
}

// HTTP request details.
type Request struct {
	// Parsed request body. Object/array for JSON, string for other content types,
	// null for no body.
	Body interface{} `json:"body,omitempty" yaml:"body,omitempty" mapstructure:"body,omitempty"`

	// Content-Type header value (e.g., application/json).
	ContentType *string `json:"contentType,omitempty" yaml:"contentType,omitempty" mapstructure:"contentType,omitempty"`

	// Request headers (keys should be lowercase).
	Headers map[string]string `json:"headers,omitempty" yaml:"headers,omitempty" mapstructure:"headers,omitempty"`

	// Request host (e.g., api.example.com).
	Host *string `json:"host,omitempty" yaml:"host,omitempty" mapstructure:"host,omitempty"`

	// HTTP method.
	Method RequestMethod `json:"method" yaml:"method" mapstructure:"method"`

	// Raw request path without query string (e.g., /users/123).
	Path string `json:"path" yaml:"path" mapstructure:"path"`

	// Extracted path parameter values.
	PathParams map[string]string `json:"pathParams,omitempty" yaml:"pathParams,omitempty" mapstructure:"pathParams,omitempty"`

	// Normalized path template with parameters (e.g., /users/{id}). Optional - can be
	// inferred.
	PathTemplate *string `json:"pathTemplate,omitempty" yaml:"pathTemplate,omitempty" mapstructure:"pathTemplate,omitempty"`

	// Query parameters as key/value pairs.
	Query map[string]interface{} `json:"query,omitempty" yaml:"query,omitempty" mapstructure:"query,omitempty"`

	// URL scheme.
	Scheme RequestScheme `json:"scheme,omitempty" yaml:"scheme,omitempty" mapstructure:"scheme,omitempty"`
}

type RequestMethod string

const RequestMethodDELETE RequestMethod = "DELETE"
const RequestMethodGET RequestMethod = "GET"
const RequestMethodHEAD RequestMethod = "HEAD"
const RequestMethodOPTIONS RequestMethod = "OPTIONS"
const RequestMethodPATCH RequestMethod = "PATCH"
const RequestMethodPOST RequestMethod = "POST"
const RequestMethodPUT RequestMethod = "PUT"
const RequestMethodTRACE RequestMethod = "TRACE"

var enumValues_RequestMethod = []interface{}{
	"GET",
	"POST",
	"PUT",
	"PATCH",
	"DELETE",
	"HEAD",
	"OPTIONS",
	"TRACE",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RequestMethod) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_RequestMethod {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_RequestMethod, v)
	}
	*j = RequestMethod(v)
	return nil
}

type RequestScheme string

const RequestSchemeHttp RequestScheme = "http"
const RequestSchemeHttps RequestScheme = "https"

var enumValues_RequestScheme = []interface{}{
	"http",
	"https",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RequestScheme) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_RequestScheme {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_RequestScheme, v)
	}
	*j = RequestScheme(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Request) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["method"]; raw != nil && !ok {
		return fmt.Errorf("field method in Request: required")
	}
	if _, ok := raw["path"]; raw != nil && !ok {
		return fmt.Errorf("field path in Request: required")
	}
	type Plain Request
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["scheme"]; !ok || v == nil {
		plain.Scheme = "https"
	}
	*j = Request(plain)
	return nil
}

// HTTP response details.
type Response struct {
	// Parsed response body. Object/array for JSON, string for other content types,
	// null for no body.
	Body interface{} `json:"body,omitempty" yaml:"body,omitempty" mapstructure:"body,omitempty"`

	// Content-Type header value.
	ContentType *string `json:"contentType,omitempty" yaml:"contentType,omitempty" mapstructure:"contentType,omitempty"`

	// Response headers (keys should be lowercase).
	Headers map[string]string `json:"headers,omitempty" yaml:"headers,omitempty" mapstructure:"headers,omitempty"`

	// HTTP status code.
	Status int `json:"status" yaml:"status" mapstructure:"status"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Response) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["status"]; raw != nil && !ok {
		return fmt.Errorf("field status in Response: required")
	}
	type Plain Response
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 599 < plain.Status {
		return fmt.Errorf("field %s: must be <= %v", "status", 599)
	}
	if 100 > plain.Status {
		return fmt.Errorf("field %s: must be >= %v", "status", 100)
	}
	*j = Response(plain)
	return nil
}
