package sitegen

const indexTemplate = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{.Title}}</title>
    <link rel="stylesheet" href="assets/style.css">
</head>
<body>
    <header>
        <div class="header-content">
            <h1>{{.Title}}</h1>
            <button id="theme-toggle" class="theme-toggle" aria-label="Toggle theme">
                <span class="sun-icon">☀️</span>
                <span class="moon-icon">🌙</span>
            </button>
        </div>
    </header>

    <main>
        <section class="stats">
            <div class="stat-card">
                <span class="stat-value">{{.Stats.TotalEndpoints}}</span>
                <span class="stat-label">Endpoints</span>
            </div>
            <div class="stat-card">
                <span class="stat-value">{{.Stats.TotalRequests}}</span>
                <span class="stat-label">Requests</span>
            </div>
            {{if .Stats.UniqueHosts}}
            <div class="stat-card">
                <span class="stat-value">{{len .Stats.UniqueHosts}}</span>
                <span class="stat-label">Hosts</span>
            </div>
            {{end}}
        </section>

        <section class="endpoints">
            <h2>Endpoints</h2>
            <table class="endpoints-table">
                <thead>
                    <tr>
                        <th>Method</th>
                        <th>Path</th>
                        <th>Requests</th>
                        <th>Status Codes</th>
                    </tr>
                </thead>
                <tbody>
                    {{range .Endpoints}}
                    <tr>
                        <td><span class="method-badge {{methodClass .Method}}">{{.Method}}</span></td>
                        <td><a href="{{.Slug}}.html" class="endpoint-link">{{.PathTemplate}}</a></td>
                        <td class="count">{{.RequestCount}}</td>
                        <td class="status-codes">
                            {{range .StatusGroups}}
                            <span class="status-badge {{statusClass .StatusCode}}">{{.StatusCode}}</span>
                            {{end}}
                        </td>
                    </tr>
                    {{end}}
                </tbody>
            </table>
        </section>

        <footer>
            <p>Generated by <a href="https://github.com/grokify/traffic2openapi">traffic2openapi</a> on {{.GeneratedAt.Format "2006-01-02 15:04:05 MST"}}</p>
        </footer>
    </main>

    <script src="assets/script.js"></script>
</body>
</html>`

const endpointTemplate = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{.Method}} {{.PathTemplate}} - {{.SiteTitle}}</title>
    <link rel="stylesheet" href="assets/style.css">
</head>
<body>
    <header>
        <div class="header-content">
            <nav class="breadcrumb">
                <a href="index.html">{{.SiteTitle}}</a>
                <span class="separator">/</span>
                <span class="current">{{.Method}} {{.PathTemplate}}</span>
            </nav>
            <button id="theme-toggle" class="theme-toggle" aria-label="Toggle theme">
                <span class="sun-icon">☀️</span>
                <span class="moon-icon">🌙</span>
            </button>
        </div>
    </header>

    <main>
        <section class="endpoint-header">
            <h1>
                <span class="method-badge {{methodClass .Method}}">{{.Method}}</span>
                <code>{{.PathTemplate}}</code>
            </h1>
            <p class="request-count">{{.RequestCount}} requests captured</p>
        </section>

        <nav class="toc">
            <h2>Status Codes</h2>
            <ul>
                {{range .StatusGroups}}
                <li>
                    <a href="#status-{{.StatusCode}}">
                        <span class="status-badge {{statusClass .StatusCode}}">{{.StatusCode}}</span>
                        <span class="count">({{len .Distinct}} unique)</span>
                    </a>
                </li>
                {{end}}
            </ul>
        </nav>

        <div class="view-toggle">
            <button class="view-btn active" data-view="deduped">Deduped View</button>
            <button class="view-btn" data-view="distinct">Distinct View</button>
        </div>

        {{range $sg := .StatusGroups}}
        <section id="status-{{$sg.StatusCode}}" class="status-section">
            <h2>
                <span class="status-badge {{statusClass .StatusCode}}">{{.StatusCode}}</span>
                Responses
            </h2>

            <!-- Deduped View -->
            <div class="view-content deduped-view active">
                {{if .Deduped}}
                <div class="request-card">
                    <div class="card-header">
                        <span class="method-badge {{methodClass .Deduped.Method}}">{{.Deduped.Method}}</span>
                        <code>{{.Deduped.PathTemplate}}</code>
                        <span class="request-count">{{.Deduped.Count}} requests</span>
                    </div>

                    {{if .Deduped.PathParamValues}}
                    <div class="params-section">
                        <h4>Path Parameters</h4>
                        <dl class="params-list">
                            {{range $key, $values := .Deduped.PathParamValues}}
                            <dt>{{$key}}</dt>
                            <dd><code>{{joinStrings $values ", "}}</code></dd>
                            {{end}}
                        </dl>
                    </div>
                    {{end}}

                    {{if .Deduped.QueryParamValues}}
                    <div class="params-section">
                        <h4>Query Parameters</h4>
                        <dl class="params-list">
                            {{range $key, $values := .Deduped.QueryParamValues}}
                            <dt>{{$key}}</dt>
                            <dd><code>{{joinStrings $values ", "}}</code></dd>
                            {{end}}
                        </dl>
                    </div>
                    {{end}}

                    {{if hasContent .Deduped.RequestBodyExample}}
                    <div class="body-section">
                        <h4>Request Body (Example)</h4>
                        <div class="code-block">
                            <button class="copy-btn" data-copy-target="deduped-req-{{$sg.StatusCode}}">Copy</button>
                            <pre id="deduped-req-{{$sg.StatusCode}}"><code class="json">{{jsonPretty .Deduped.RequestBodyExample}}</code></pre>
                        </div>
                    </div>
                    {{end}}

                    {{if hasContent .Deduped.ResponseBodyExample}}
                    <div class="body-section">
                        <h4>Response Body (Example)</h4>
                        <div class="code-block">
                            <button class="copy-btn" data-copy-target="deduped-res-{{$sg.StatusCode}}">Copy</button>
                            <pre id="deduped-res-{{$sg.StatusCode}}"><code class="json">{{jsonPretty .Deduped.ResponseBodyExample}}</code></pre>
                        </div>
                    </div>
                    {{end}}
                </div>
                {{end}}
            </div>

            <!-- Distinct View -->
            <div class="view-content distinct-view">
                {{range $idx, $req := .Distinct}}
                <div class="request-card">
                    <div class="card-header">
                        <span class="method-badge {{methodClass $req.Method}}">{{$req.Method}}</span>
                        <code>{{$req.Path}}</code>
                        {{if $req.ID}}<span class="request-id">ID: {{$req.ID}}</span>{{end}}
                    </div>

                    {{if hasContent $req.QueryParams}}
                    <div class="params-section">
                        <h4>Query Parameters</h4>
                        <dl class="params-list">
                            {{range $key, $value := $req.QueryParams}}
                            <dt>{{$key}}</dt>
                            <dd><code>{{json $value}}</code></dd>
                            {{end}}
                        </dl>
                    </div>
                    {{end}}

                    {{if hasContent $req.RequestHeaders}}
                    <details class="headers-section">
                        <summary>Request Headers</summary>
                        <pre><code>{{formatHeaders $req.RequestHeaders}}</code></pre>
                    </details>
                    {{end}}

                    {{if hasContent $req.RequestBody}}
                    <div class="body-section">
                        <h4>Request Body</h4>
                        <div class="code-block">
                            <button class="copy-btn" data-copy-target="distinct-req-{{$sg.StatusCode}}-{{$idx}}">Copy</button>
                            <pre id="distinct-req-{{$sg.StatusCode}}-{{$idx}}"><code class="json">{{jsonPretty $req.RequestBody}}</code></pre>
                        </div>
                    </div>
                    {{end}}

                    {{if hasContent $req.ResponseHeaders}}
                    <details class="headers-section">
                        <summary>Response Headers</summary>
                        <pre><code>{{formatHeaders $req.ResponseHeaders}}</code></pre>
                    </details>
                    {{end}}

                    {{if hasContent $req.ResponseBody}}
                    <div class="body-section">
                        <h4>Response Body</h4>
                        <div class="code-block">
                            <button class="copy-btn" data-copy-target="distinct-res-{{$sg.StatusCode}}-{{$idx}}">Copy</button>
                            <pre id="distinct-res-{{$sg.StatusCode}}-{{$idx}}"><code class="json">{{jsonPretty $req.ResponseBody}}</code></pre>
                        </div>
                    </div>
                    {{end}}
                </div>
                {{end}}
            </div>
        </section>
        {{end}}

        <footer>
            <p>Generated by <a href="https://github.com/grokify/traffic2openapi">traffic2openapi</a></p>
        </footer>
    </main>

    <script src="assets/script.js"></script>
</body>
</html>`
